### ISSUE TITLE
Lan cache blocks for logins to origen Riot and more

### ISSUE THREAD

**Issue by Coffee0297** [lancachenet/lancache-dns#134]
Hey, so im running a lan cache for a small lan party with 300 ppl, and we have a issue with it blocking logins to some online providers. 
Like steam, Origen, Riot. 

```Nmap scan report for 10.0.0.45
Host is up (0.000054s latency).
Not shown: 995 closed ports
PORT    STATE SERVICE
22/tcp  open  ssh
53/tcp  open  domain
80/tcp  open  http
111/tcp open  rpcbind
443/tcp open  https
```

System specs
```
Ubuntu 18.04.6 LTS
1tb NVME
AMD Ryzen 7 3800X
32gb ram

interfaces in a bond to get 2gbit theoretical
intel 82574L 
Realtek RTL8111/8168/8411 PCI
```
lmk what logs you wuld want

**Comment by Coffee0297** [comment]
Docker compose start script


```
version: '2'
services:
  dns:
    image: lancachenet/lancache-dns:latest
    env_file: .env
#    restart: unless-stopped
    ports:
      - ${DNS_BIND_IP}:53:53/udp
      - ${DNS_BIND_IP}:53:53/tcp
  sniproxy:
    image: lancachenet/sniproxy:latest
    env_file: .env
#    restart: unless-stopped
    ports:
      - 443:443/tcp
  monolithic:
    image: lancachenet/monolithic:latest
    env_file: .env
#    restart: unless-stopped
    ports:
      - 80:80/tcp
    volumes:
      - ${CACHE_ROOT}/cache:/data/cache
      - ${CACHE_ROOT}/logs:/data/logs
```
