### ISSUE TITLE
UPSTREAM_DNS does not support hostnames or custom ports

### ISSUE THREAD

**Issue by MiningMarsh** [lancachenet/lancache-dns#145]
I want to insert lancache-dns into my DNS chain, but it doesn't allow flexible enough UPSTREAM_DNS declarations.

I would like to be able to do something like this:
```yaml
lancache-dns:
    extra_hosts:
        - some_hostname:host-gateway
    environment:
        - UPSTREAM_DNS=some_hostname:953
```

This would allow me to easily forward to another DNS resolver on the same host machine (or some other container) without needing to know the gateway IP ahead of time.  It would also allow me to more easily chain resolvers after lancache-dns; in my case I have an instance of stubby that bridges DNS to DNS-over-HTTPS for any device on my home network.

Right now, if you specify anything other than a plain IP, the container dies on startup:
```
local.lancache.dns    | IP address: some_host:953 is not valid
```
